universe = container
container_image = osdf:///ospool/ap40/data/ian.ross/metl.sif

executable = finetune.sh
output = $(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# request_disk should be at least 10x the size of the input files
# processing propose typically uses about 3.5 GB of CPU memory and 8GB of GPU memory
# add cpus=xx disk=yy memory=zz on the submit command line to override these defaults
request_disk = $(disk:5GB)
request_memory = $(memory:6GB)
request_cpus = $(cpus:1)
request_gpus = 1
gpus_minimum_capability = 7.5
gpus_minimum_memory = 8192

environment = "WANDB_API_KEY=123"

+is_resumable = true

executable = /bin/bash
transfer_executable = false
arguments = pretrain.sh

transfer_input_files = pretrain.sh
transfer_output_files = output
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT

output = $(CLUSTERID).out
error = $(CLUSTERID).err
log = metl.log

queue
